# Site settings
title: omnizya
description: >
  Tech for Better Life.
lang: en
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://omnizya.com" # the base hostname & protocol for your site
cover: /assets/images/cover/omnigram.png
fbapp: 315781848821058

author:
  fullname: Mohamed Moughamir
  github: omnizya
  linkedin: moughamir
  instagram: omnizya
  twitter: omnizya
  disqus: omnizya


# Syntax highlighting
highlightstyle: 'solarized_dark'
styles: [darkula, solarized_dark]
# Addons
fontawesomeId: '27f81a8a19'
# Handling Reading
exclude: ["README.md", "README.html", "vendor"]

# Build settings
highlighter: null
markdown: kramdown
