# Site settings
title: Moughamir Mohamed
email: moughamir@gmail.com
description: >
  Awesome description for my Personal Page/Blog on GitHub
  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moughamir.github.com" # the base hostname & protocol for your site

#
encoding: "utf-8"
#Social Netwokk accounts
twitter: omnizya
github: moughamir
google: +MohamedMoughamir
faceboook: odin911

# Build settings
markdown: kramdown

# Serv
port: 8095
host: omnizya.dev

